#!/bin/bash
#SBATCH --export=ALL # export all environment variables to the batch job.
#SBATCH -p mrcq # submit to the serial queue
#SBATCH -A Research_Project-MRC190311 # research project to submit under.
#SBATCH --mail-type=END # send email at job completion
#SBATCH --output=Jobreports/mungeT2D.out
#SBATCH --error=Jobreports/mungeT2D.err
#SBATCH --job-name=mungeT2D
#SBATCH --nodes=1
#SBATCH --mem=20G
#SBATCH --ntasks=2
#SBATCH --time=0-15:00:00
#SBATCH --array=2

############################################################################################
#       munge_MSS GWAS
############################################################################################

#define the path
RscriptsPath="/lustre/home/sww208/GoDMC/HormiseGWAS/Rscripts"

module purge
source "/gpfs/ts0/shared/software/Miniconda3/23.5.2-0/etc/profile.d/conda.sh"
conda activate RGreatSquareRoot

# Munge for filtered datasets generated by Siyi ###################################################
# Under the path of /lustre/home/sww208/GoDMC/GADatasets/OtherGWASstats/
if [ "${SLURM_ARRAY_TASK_ID}" == 1 ] ;then
    DataPath="/lustre/home/sww208/GoDMC/GADatasets/OtherGWASstats/"
    echo "Dealing with datasets localed in $DataPath"
    for ID in PD_2019 NEA_2021 CEA_2021 CRP_2022 INT_2017 MDD_2025
    do  
        echo "$ID======================================================"
        Rscript $RscriptsPath/munge_MSS.R \
                            $DataPath \
                            $ID.LDSCinput \
                            $ID
    done
fi


# Munge for filtered datasets generated by Ann ###################################################
# Under the path of /lustre/home/sww208/GoDMC/GADatasets/GWASstatsFiltered
if [ "${SLURM_ARRAY_TASK_ID}" == 2 ] ;then
    DataPath="/lustre/home/sww208/GoDMC/GADatasets/GWASstatsFiltered"
    echo "Dealing with datasets localed in $DataPath"
    for ID in BMI_2018 BP_2024 FG_2021 FI_2021 G2H_2021 HBAC1_2021 HEIGHTb_2022 HEIGHTc_2022 MD_2025 SCZ_2022;
    do  
        echo "$ID======================================================"
        Rscript $RscriptsPath/munge_MSS.R \
                            $DataPath \
                            $ID.b37.filtered \
                            $ID
    done

    # AD_2021.b37.filtered ###################################################
    # chromosome      base_pair_location      effect_allele   other_allele    z_score standard_error  effect_allele_frequency p_value n
    awk -v OFS='\t' '{print $1,$2,$3,$4,$5,$7,$8,$9}' AD_2021.b37.filtered > AD_2021.b37.filtered.noNA
    Rscript $RscriptsPath/munge_MSS.R $DataPath AD_2021.b37.filtered.noNA AD_2021

    # T2D_2024.b37.filtered ###################################################
    # Chromsome       Position        effect_allele   non_effect_allele       Beta    SE      FRQ     P       N_CAS   N_CON   Neff
    awk -v OFS='\t' '{print $1":"$2,$1,$2,$3,$4,$5,$7,$8,$9,$10,$11}' T2D_2024.b37.filtered > T2D_2024.b37.filtered.SNP
    sed 's/Chromsome:Position/SNP/' T2D_2024.b37.filtered.SNP
    Rscript $RscriptsPath/munge_MSS.R $DataPath T2D_2024.b37.filtered.SNP T2D_2024

fi